/// Credit card types
typedef NS_ENUM(NSInteger, UQUIKPaymentOptionType) {
    UQUIKPaymentOptionTypeUnknown = 0,
    UQUIKPaymentOptionTypeAMEX,
    UQUIKPaymentOptionTypeDinersClub,
    UQUIKPaymentOptionTypeDiscover,
    UQUIKPaymentOptionTypeMasterCard,
    UQUIKPaymentOptionTypeVisa,
    UQUIKPaymentOptionTypeJCB,
    UQUIKPaymentOptionTypeLaser,
    UQUIKPaymentOptionTypeMaestro,
    UQUIKPaymentOptionTypeUnionPay,
    UQUIKPaymentOptionTypeSolo,
    UQUIKPaymentOptionTypeSwitch,
    UQUIKPaymentOptionTypeUKMaestro,
    UQUIKPaymentOptionTypePayPal,
    UQUIKPaymentOptionTypeCoinbase,
    UQUIKPaymentOptionTypeVenmo,
    UQUIKPaymentOptionTypeApplePay,
};
